# Site
name: "Gạch bông gió chống mưa Gạch bánh ú"
title: "Gạch Bông Gió Chống Mưa Blog"
description: "Gạch bông gió chống mưa là loại gạch bông gió chống hắt mưa nhưng vẫn đảm bảo thông gió lấy sáng!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
url: https://gachbonggiochongmua.onrender.com
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: cts@cementtile.vn

# Authors
authors:
  sal:
    name: David Nguyen
    display_name: David Nguyen
    avatar: 'assets/images/avatar-sal.png'
    email: cans@cementtile.vn
    web: https://cementtiles.vn
    twitter: https://twitter.com/vietnamtiles
    description: "Gạch bông gió chống mưa là loại gạch bông gió chống hắt mưa nhưng vẫn đảm bảo thông gió lấy sáng!"
  john:
    name: Nguyen Ca
    display_name: Nguyen Ca  
    avatar: 'assets/images/avatar.png'
    email: cts@cementtile.vn
    web: https://nguyensoncavn.com
    twitter: https://twitter.com/cementtilevn
    description: "Gạch bông gió chống mưa là loại gạch bông gió chống hắt mưa nhưng vẫn đảm bảo thông gió lấy sáng!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-admin
    
# Archives
jekyll-archives:
  enabled: all
   # - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
